# Generated by Django 4.2.1 on 2023-05-09 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(unique=True)),
                ('gmail', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatar/archivos')),
                ('ubicacion', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarrerasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pemsum', models.FileField(upload_to='pemsun/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='DirectorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_reverce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directores',
            },
        ),
        migrations.CreateModel(
            name='EscuelasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('carreras', models.ManyToManyField(blank=True, related_name='carreras_reverce', to='users.carrerasmodels')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_reverce', to='users.directormodels')),
            ],
            options={
                'verbose_name': 'escuela',
                'verbose_name_plural': 'escuelas',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_estudiante_revercs', to='users.carrerasmodels')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuela_estudent', to='users.escuelasmodels')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_estudiantes_reverce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='MateriasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'materias',
            },
        ),
        migrations.CreateModel(
            name='SemestreModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'semestre',
                'verbose_name_plural': 'semestres',
            },
        ),
        migrations.CreateModel(
            name='SecionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ManyToManyField(to='users.estudiantesmodels')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesion_reverce', to='users.materiasmodels')),
            ],
            options={
                'verbose_name': 'secion',
                'verbose_name_plural': 'seciones',
            },
        ),
        migrations.CreateModel(
            name='ProfesoresModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_user_reverce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profesore',
                'verbose_name_plural': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Notamodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('estudiate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_nota_reverce', to='users.estudiantesmodels')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_reverce', to='users.materiasmodels')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_reverce', to='users.profesoresmodels'),
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='secion',
            field=models.ManyToManyField(blank=True, related_name='secion_reverce', to='users.secionmodels'),
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='semestre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_reverce', to='users.semestremodels'),
        ),
        migrations.AddField(
            model_name='escuelasmodels',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='estudiantes_reverce', to='users.estudiantesmodels'),
        ),
        migrations.AddField(
            model_name='escuelasmodels',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='profesores_reverce', to='users.profesoresmodels'),
        ),
        migrations.AddField(
            model_name='carrerasmodels',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='materia_carreras_reverce', to='users.materiasmodels'),
        ),
    ]
