# Generated by Django 4.2 on 2023-06-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestremodels',
            name='materia',
        ),
        migrations.AddField(
            model_name='semestremodels',
            name='materia',
            field=models.ManyToManyField(related_name='materia_semestres', to='users.materiasmodels'),
        ),
    ]
