# Generated by Django 4.2 on 2023-06-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestremodels',
            name='materia',
            field=models.ManyToManyField(blank=True, related_name='materia_semestres', to='users.materiasmodels'),
        ),
    ]
