# Generated by Django 4.2.1 on 2023-05-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_materiasmodels_secion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_online',
            new_name='is_profesor',
        ),
        migrations.AddField(
            model_name='user',
            name='is_registro',
            field=models.BooleanField(default=False),
        ),
    ]
