# Generated by Django 4.2 on 2023-06-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_semestremodels_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiasmodels',
            name='semestre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_semestre_reverce', to='users.semestremodels'),
        ),
    ]
