# Generated by Django 4.2 on 2023-12-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_escuelasmodels_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='militar',
            field=models.BooleanField(default=False),
        ),
    ]
