# Generated by Django 4.2 on 2023-06-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_semestremodels_materia_semestremodels_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestremodels',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_carrera', to='users.carrerasmodels'),
            preserve_default=False,
        ),
    ]
