# Generated by Django 4.2.1 on 2023-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_online_user_is_profesor_user_is_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secionmodels',
            name='estudiante',
            field=models.ManyToManyField(related_name='estudiante_secion_reverce', to='users.estudiantesmodels'),
        ),
    ]
