# Generated by Django 4.2 on 2023-11-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_materiasmodels_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='militar',
            field=models.BooleanField(default=False),
        ),
    ]
