# Generated by Django 4.2 on 2023-11-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_datospersonales_militar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
