# Generated by Django 4.2 on 2023-06-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_materiasmodels_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiasmodels',
            name='semestre',
        ),
    ]
