# Generated by Django 4.2 on 2023-06-10 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_materiasmodels_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasmodels',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materia_semestre_reverce', to='users.semestremodels'),
            preserve_default=False,
        ),
    ]
