# Generated by Django 4.2 on 2023-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_datospersonales_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datossiesmilitar',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datossiesmilitar',
            name='ultimo_asenso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
