# Generated by Django 4.2 on 2023-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_datossiesmilitar_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='Secion',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='alergico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='alguna_discapasidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('s', 'SOLTERO'), ('c', 'CASADO'), ('u', 'UNION LIBRE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='funcion_desenpeña',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='militar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='no_cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'MASCULINO'), ('f', 'FEMENINO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
