# Generated by Django 4.2.1 on 2023-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_secionmodels_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelasmodels',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escuelasmodels',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada/'),
        ),
    ]
