# Generated by Django 4.2 on 2023-06-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_materiasmodels_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestremodels',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudoante_semestre_reverce', to='users.estudiantesmodels'),
            preserve_default=False,
        ),
    ]
