# Generated by Django 4.2 on 2023-06-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_semestremodels_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestremodels',
            name='estudiante',
        ),
    ]
