# Generated by Django 4.2 on 2023-06-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_semestremodels_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiasmodels',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='materiasmodels',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='materiasmodels',
            name='semestre',
        ),
        migrations.AddField(
            model_name='carrerasmodels',
            name='id_escuela',
            field=models.ManyToManyField(to='users.escuelasmodels'),
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='credito',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesoresmodels',
            name='materia',
            field=models.ManyToManyField(to='users.materiasmodels'),
        ),
        migrations.RemoveField(
            model_name='semestremodels',
            name='carrera',
        ),
        migrations.AddField(
            model_name='semestremodels',
            name='carrera',
            field=models.ManyToManyField(to='users.carrerasmodels'),
        ),
    ]
