# Generated by Django 4.2 on 2023-06-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_materiasmodels_carrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrerasmodels',
            name='id_escuela',
        ),
        migrations.RemoveField(
            model_name='materiasmodels',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='profesoresmodels',
            name='materia',
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_materia_reverce', to='users.carrerasmodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_reverce', to='users.profesoresmodels'),
        ),
        migrations.AddField(
            model_name='materiasmodels',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materia_semestre_reverce', to='users.semestremodels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semestremodels',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estudoante_semestre_reverce', to='users.estudiantesmodels'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='semestremodels',
            name='carrera',
        ),
        migrations.AddField(
            model_name='semestremodels',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semestre_carrera', to='users.carrerasmodels'),
            preserve_default=False,
        ),
    ]
