# Generated by Django 4.2 on 2023-06-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_carrerasmodels_id_escuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasmodels',
            name='credito',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
