# Generated by Django 4.2 on 2023-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_materiasmodels_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiasmodels',
            name='credito',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
