# Generated by Django 4.2 on 2023-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotasProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.PositiveIntegerField(blank=True, null=True)),
                ('participacion', models.PositiveIntegerField(blank=True, null=True)),
                ('parcial', models.PositiveIntegerField(blank=True, null=True)),
                ('filnal_ex', models.PositiveIntegerField(blank=True, null=True)),
                ('nota_final', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
