# Generated by Django 4.2.1 on 2023-05-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_secionmodels_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.PositiveIntegerField(blank=True, null=True)),
                ('participacion', models.PositiveIntegerField(blank=True, null=True)),
                ('parcial', models.PositiveIntegerField(blank=True, null=True)),
                ('filnal_ex', models.PositiveIntegerField(blank=True, null=True)),
                ('alunno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunno_reverce', to='users.estudiantesmodels')),
            ],
        ),
    ]
