# Generated by Django 4.2 on 2023-06-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasprofesor',
            name='alunno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunno_reverce', to='users.estudiantesmodels'),
        ),
        migrations.AddField(
            model_name='notasprofesor',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_cecion_reverce', to='users.materiasmodels'),
        ),
    ]
