# Generated by Django 4.2.1 on 2023-05-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_secionmodels_estudiante'),
        ('inicio', '0002_alter_notasprofesor_alunno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasprofesor',
            name='secion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secion_nota_reverce', to='users.secionmodels'),
        ),
    ]
