# Generated by Django 4.2.1 on 2023-05-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_secionmodels_estudiante'),
        ('inicio', '0003_notasprofesor_secion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasprofesor',
            name='secion',
        ),
        migrations.AddField(
            model_name='notasprofesor',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_cecion_reverce', to='users.materiasmodels'),
        ),
    ]
