# Generated by Django 4.2.1 on 2023-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_notasprofesor_secion_notasprofesor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasprofesor',
            name='nota_final',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
