# Generated by Django 4.2.1 on 2023-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_notasprofesor_nota_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasprofesor',
            name='nota_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
