# Generated by Django 4.2.1 on 2023-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_notasprofesor_nota_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasprofesor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
